import { prisma } from "@/lib/prisma";
import { notFound } from "next/navigation";
import { money } from "@/lib/finance";
import { format } from "date-fns";

export default async function PurchaseInvoicePage({ params }: { params: { id: string } }) {
  const purchase = await prisma.purchase.findUnique({
    where: { id: params.id },
    include: {
      supplier: true,
      items: {
        include: { product: true }
      }
    }
  });

  if (!purchase) return notFound();

  return (
    <div className="bg-white text-black p-8 max-w-4xl mx-auto min-h-screen font-sans print:p-0 print:m-0 print:w-full print:shadow-none">
      <div className="flex justify-between items-start border-b-2 border-black pb-6 mb-6">
        <div>
          <h1 className="text-3xl font-bold uppercase tracking-tight">Rajesh Icecream</h1>
          <p className="text-gray-600 mt-1">Official Purchase Invoice</p>
        </div>
        <div className="text-right">
          <h2 className="text-xl font-semibold">INVOICE #{purchase.invoiceNumber}</h2>
          <p className="text-gray-600">Date: {format(purchase.purchaseDate, "dd MMM yyyy")}</p>
          <button onClick={() => window.print()} className="mt-2 text-sm bg-blue-600 text-white px-4 py-1.5 rounded print:hidden">Print Invoice</button>
        </div>
      </div>

      <div className="mb-8">
        <h3 className="text-sm font-semibold text-gray-500 uppercase">Supplier Details</h3>
        <p className="text-lg font-medium">{purchase.supplier.name}</p>
        {purchase.supplier.contactNumber && <p className="text-gray-700">Contact: {purchase.supplier.contactNumber}</p>}
        {purchase.supplier.gstNumber && <p className="text-gray-700">GST: {purchase.supplier.gstNumber}</p>}
      </div>

      <table className="w-full text-left border-collapse mb-8">
        <thead>
          <tr className="bg-gray-100 text-sm uppercase">
            <th className="py-3 px-4 font-semibold border-b border-gray-300">Product</th>
            <th className="py-3 px-4 font-semibold border-b border-gray-300 text-right">Qty</th>
            <th className="py-3 px-4 font-semibold border-b border-gray-300 text-right">Unit Price</th>
            <th className="py-3 px-4 font-semibold border-b border-gray-300 text-right">Total</th>
          </tr>
        </thead>
        <tbody>
          {purchase.items.map((item) => (
            <tr key={item.id} className="border-b border-gray-200">
              <td className="py-3 px-4">{item.product.name} ({item.product.category})</td>
              <td className="py-3 px-4 text-right">{item.quantity}</td>
              <td className="py-3 px-4 text-right">{money(item.costPrice)}</td>
              <td className="py-3 px-4 text-right font-medium">{money(item.totalPrice)}</td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr>
            <td colSpan={3} className="py-4 px-4 text-right font-bold text-lg">Total Amount:</td>
            <td className="py-4 px-4 text-right font-bold text-xl">{money(purchase.totalAmount)}</td>
          </tr>
        </tfoot>
      </table>

      {purchase.note && (
        <div className="mt-8 bg-gray-50 p-4 rounded border border-gray-200">
          <h4 className="font-semibold text-gray-700 mb-1">Notes:</h4>
          <p className="text-gray-600">{purchase.note}</p>
        </div>
      )}

      {purchase.attachmentPath && (
        <div className="mt-4 text-sm text-gray-500">
          Attachment stored at: {purchase.attachmentPath}
        </div>
      )}

      <div className="mt-16 text-center text-sm text-gray-500 pt-8 border-t border-gray-200">
        Generated by Rajesh Icecream Enterprise ERP Manager
      </div>
    </div>
  );
}
